#!/bin/sh

ITMO=itmo


FILE1=/tmp/itmo1-$$
FILE2=/tmp/itmo2-$$
ERROR=/tmp/itmo-err-$$

GETTEXT="gettext -d itmo_UI"

which gdialog 2> /dev/null && DIALOG=gdialog || DIALOG=dialog

end () {
       rm -f $FILE1 $FILE2 $ERROR
       exit
}

while true
do
        $DIALOG --inputbox "`gettext \"Enter amount:\"`" 8 35 2> $FILE1 || end
	if cat $FILE1 | $ITMO > $FILE2 2>$ERROR
	then
		MSG1="`gettext \"Sender:\"` `echo $SENDER`\\n\\n`gettext \"Continue?\"`"
		$MSG1 8 35 2>$ITMO
		$DIALOG --yesno "$MSG1" 7 20 || end
		MSG2="`gettext \"Receiver:\"` `echo $RECEIVER`\\n\\n`gettext \"Continue?\"`"
		$DIALOG --yesno "$MSG2" 7 20 || end
		MSG3="`gettext \"Transaction:\"` `echo $TRANSACTION`\\n\\n`gettext \"Continue?\"`"
		$DIALOG --yesno "$MSG3" 7 20 || end
		MSG="`gettext \"Amount:\"` `cat $FILE2`\\n\\n`gettext \"Continue?\"`"
		$DIALOG --yesno "$MSG" 7 20 || end
	else
		MSG="`gettext \"Error:\"`\\n\\n`cat $ERROR`\\n\\n`gettext \"Continue?\"`"
		$DIALOG --yesno "$MSG" 10 35 || end
	fi
done
