#!/bin/sh

pfile="./passwd"
PASSWD=$(cat "$pfile")

echo "Ethereum Wallet Transfer"

ETH=$(which geth &>/dev/null) 
check_geth() {
    STATUS=""
    if [ -z $ETH ] && [ ! "$(ps -A | grep ether*)" ];  
    then
        STATUS="You need to install Ethereum CLI based on GoLang, or run Ethereum Wallet App"
    else 
        STATUS="OK"
    fi
    echo $STATUS
}

echo "Transaction"

transaction(){
	SENDER=$1
	RECEIVER=$2
	AMOUNT=$3
	./geth --exec "personal.unlockAccount('$SENDER', '$PASSWD')" attach > /dev/null	
	TRANSACTION=`./geth --testnet --fast -exec "eth.sendTransaction({from: '$SENDER', to: '$RECEIVER', value: web3.toWei('$AMOUNT', 'ether')})" attach`
	echo $TRANSACTION
}


help () {
    printf "Script: "$0" provides the possibility to send ether from one account to another\n"
}



cli_main(){

if [ ! -z $1 ] && [ $1 = "-h" ];
    then
        help
        exit
fi

STATUS=$(check_geth)
    if [[ $STATUS != *"OK" ]] || $([ ! -z $1 ] );
    then
        echo $STATUS
        exit 
fi

if [ ! -z $1 ];
    then
        if [ $1 = "-a" ];
then
	    TRANSACTION="$(send $2 $3 $4)"
	    echo $TRANSACTION
	    exit	
	fi
fi


while true
do
	printf "Enter SENDER account:\n"
	read SENDER
	#echo "Your Wallet is: $sen"

	printf "Enter RECEIVER account:\n"
	read RECEIVER
	#echo "Your Wallet is: $rec"

	printf "Enter AMOUNT to send:\n"
	read AMOUNT
	#echo "Amount to send is : $amount"

	TRANSACTION="$(transaction $SENDER $RECEIVER $AMOUNT)"
	echo "Transaction code is:"
	echo $TRANSACTION

	printf "Do you want make another transaction? (Y/N).\n"
	read ANS
	if [ $ANS != "Y" ];
        then
	    echo "" > "$pfile"
            exit
	fi

done

} 


cli_main $*


 

